version: 2.1

jobs:
  deploy_sam:
    docker:
      - image: public.ecr.aws/sam/build-python3.11
    steps:
      - checkout
      - run:
          name: SAM Build
          command: |
            cd sam
            sam build
      - run:
          name: SAM Deploy
          command: |
            cd sam
            sam deploy \
              --no-confirm-changeset \
              --no-fail-on-empty-changeset \
              --resolve-s3 \
              --region eu-central-1 \
              --parameter-overrides Stage=dev

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply if .tf files changed
          command: |
            git fetch origin main
            if git diff --name-only origin/main...HEAD | grep '\.tf$'; then
              cd terraform
              terraform init
              terraform apply -auto-approve
            else
              echo "No Terraform changes detected. Skipping apply."
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_sam:
          filters:
            branches:
              only: main
      - terraform_apply:
          filters:
            branches:
              only: main
