version: 2.1

jobs:
  deploy_sam:
    docker:
      - image: public.ecr.aws/sam/build-python3.11
    steps:
      - checkout
      - run:
          name: SAM Build
          command: |
            cd sam
            sam build
      - run:
          name: SAM Deploy
          command: |
            cd sam
            sam deploy \
              --no-confirm-changeset \
              --no-fail-on-empty-changeset \
              --resolve-s3 \
              --region eu-central-1 \
              --parameter-overrides Stage=dev

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply if new .tf files added
          command: |
            git fetch origin main
            NEW_TF_FILES=$(git diff --name-status origin/main...HEAD | grep '^A' | grep '\.tf$' || true)
            if [ -n "$NEW_TF_FILES" ]; then
              echo "Detected new Terraform files:"
              echo "$NEW_TF_FILES"
              cd terraform
              terraform init
              terraform apply -auto-approve
            else
              echo "No new Terraform files added. Skipping apply."
            fi


workflows:
  version: 2
  deploy:
    jobs:
      - deploy_sam:
          filters:
            branches:
              only: main
      - terraform_apply:
          filters:
            branches:
              only: main
